config/routes.rb
Rails.application.routes.draw do

	resources :charges, only: [:new, :create]
	resources :wikis do
		resources :collaborators, only: [:create, :destroy]
	end

	get 'my_wikis' => 'wikis#my_wikis'
	get 'cancel_charge' => 'charges#cancel'
	get 'cancelling_charge' => 'charges#cancelling'

  devise_for :users, controllers: {registrations: "registrations"}
  get 'about' => 'welcome#about'

	root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
	extend FriendlyId

	friendly_id :title, use: :slugged

  belongs_to :user
	has_many :collaborators
	has_many :users, through: :collaborators

	default_scope { order('updated_at DESC') }

	validates :title, presence: true, length: {minimum: 2}
	validates :body, presence: true, length: {minimum: 20}
	validates :user, presence: true

	def possible_collaborators
		#User.all.reject{|u| u.id != user.id || collaborators.include?(u.id)}
	end

	def collaborator_name(user_id)
		if user_id
			c = collaborators.find_by_user_id(user_id)
			return c
		else
			collaborators.first
		end
	end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
	# before_action :authenticate_user!

  def index
		# Pundit Wiki Policy Scope
		@wikis = policy_scope(Wiki)
		# @wikis = Wiki.all
		# authorize @wikis
  end

	def my_wikis
		@user = current_user
	end

  def show
		@wiki = Wiki.friendly.find(params[:id])
		authorize @wiki
  end

  def new
		@wiki = Wiki.new
		authorize @wiki
  end

  def edit
		@wiki = Wiki.friendly.find(params[:id])
		#redirect to new_user_registration_path if no current_user
		# if !current_user
		# 	redirect_to(new_user_registration_path)
		# end
		authorize @wiki
		@collaborators = @wiki.collaborators
		# @collaborator = @wiki.collaborators.find_by_user_id(params[:user_id])
		# @collab_to_remove = @wiki.collaborator(user_id)
  end

	def create
		@wiki = Wiki.new(wiki_params)
		authorize @wiki
		@wiki.user = current_user

		if @wiki.private && @wiki.user.standard?
			flash[:alert] = "You need a Premium account to make your Wiki private."
			render :new
		else
			if @wiki.save
				flash[:notice] = "Wiki was saved successfully."
				redirect_to @wiki
			else
				flash[:alert] = "There was an error saving the wiki. Please try again."
				render :new
			end
		end
	end

	def update
		@wiki = Wiki.friendly.find(params[:id])
		authorize @wiki
		@wiki.assign_attributes(wiki_params)

		# FriendlyId will recreate slug if nil
		@wiki.slug = nil

		if @wiki.private && @wiki.user.standard?
			flash[:alert] = "You need a Premium account to make your Wiki private."
			render :edit
		else
			if @wiki.save
				flash[:notice] = "\"#{@wiki.title}\" wiki was updated successfully."
				redirect_to @wiki
			else
				flash[:alert] = "There was an error in saving the updates to the #{@wiki.title} wiki. Please try again."
				render :edit
			end
		end
	end

	def destroy
		@wiki = Wiki.friendly.find(params[:id])
		authorize @wiki

		if @wiki.destroy
			flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
			redirect_to wikis_path
		else
			flash[:alert] = "There was an error deleting the \"#{@wiki.title}\" wiki. Please try again."
			render :show
		end
	end

	private
	def wiki_params
		params.require(:wiki).permit(:title, :body, :private, :user_id, :slug)
	end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
	<% if wiki.errors.any? %>
		<div class="alert alert-danger">
			<h4><%= pluralize(wiki.errors.count, "Error") %>:</h4>
			<ul>
				<% wiki.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= form_group_tag(wiki.errors[:title]) do %>
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control", placeholder: "Enter wiki title" %>
	<% end %>
	<%= form_group_tag(wiki.errors[:body]) do %>
		<%= f.label :body %>
		<%= f.text_area :body, class: "form-control", placeholder: "Enter wiki body", rows: 12 %>
	<% end %>
	<% if current_user.admin? || current_user.premium? %>
		<% if current_user.admin? || wiki.user == current_user || wiki.user == nil %>
			<div class="form-group">
				<%= f.label :private, class: "checkbox" do %>
				Private Wiki <%= f.check_box :private, style: "margin-left: 10px;" %>
				<% end %>
			</div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.submit "Save", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
	<div class="col-md-4">
		<h4>Guidelines for Wikis</h4>
		<p class="lead">Here are some general guidelines and good ideas for posting new wikis.</p>
		<br />
		<% if current_user && @wiki.user == current_user && @wiki.private %>
			<%= render partial: 'collaborators/form', locals: {collaborator: @wiki.collaborators.new, wiki: @wiki} %>

			<h4>Collaborators:</h4>
			<table width="100%">
				<% @wiki.collaborators.all.each do |collab| %>
				<tr>
					<td>
						<%= link_to "Remove", "/wikis/#{@wiki.id}/collaborators/#{collab.id}", method: :delete, class: "btn btn-danger btn-xs", data: {confirm: "Are you sure you want to remove #{collab.user.name} as a collaborator?"} %>
					</td>
					<td>
						<h5 class="text-muted">
							<%= "#{collab.user.name} - (#{collab.user.email})" %>
						</h5>
					</td>
				</tr>
				<% end %>
			</table>
		<% end %>
	</div>

	<div class="col-md-8">
		<%= render partial: 'form', locals: {wiki: @wiki} %>
	</div>
</div>

app/views/wikis/index.html.erb
<div class="text-center">
	<h1 class="text-center public-wikis-heading">Public Wikis</h1>
	<%= link_to "New Wiki", new_wiki_path, class: "btn btn-primary btn-lg new-public-wiki" %>
</div>
<br />
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table">
			<div class="media">
				<div class="media-body">
					<% @wikis.each do |wiki| %>
						<% if wiki.private == nil || wiki.private == false || (current_user ? current_user.admin? : nil) %>
							<tr>
								<td>
									<h4 class="media-heading">
									<%= link_to wiki.title, wiki %>
										<small>
											<% if wiki.private == true %>
											 	- <strong>Private</strong>
											<% end %>
											- Updated <%= time_ago_in_words(wiki.updated_at) %> ago.
										</small>
									</h4>
									<small>Created by <%= wiki.user.name %></small>
								</td>
								<td width="3rem">
									<% if current_user %>
										<%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-default" %>
									<% end %>
								</td>
							</tr>
						<% end %>
					<% end %>
				</div>
			</div>
		</table>
	</div>
</div>
<!-- <div class="text-center">
	<%= link_to "New Wiki", new_wiki_path, class: "btn btn-primary btn-lg" %>
</div> -->

app/views/wikis/my_wikis.html.erb
<div class="jumbotron home-jumbo">
	<h2 class="text-center">My Wikis</h2>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="text-center">
			<%= link_to "New Wiki", new_wiki_path, class: "btn btn-primary btn-lg" %>
		</div>
		<table class="table">
			<div class="media">
				<div class="media-body">
					<h4 class="text-center">My Public Wikis</h4>
					<% @user.wikis.each do |wiki| %>
						<% if wiki.private == nil || wiki.private == false %>
							<tr>
								<td>
									<h4 class="media-heading"><%= link_to wiki.title, wiki %>
									<small>
										 - Updated <%= time_ago_in_words(wiki.updated_at) %> ago.
									 </small>
								 </h4>
							 </td>
								<td width="3rem"><%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-default" %></td>
								<!-- <td width="3rem"><%= link_to "Delete", wiki, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this wiki?"} %></td> -->
							</tr>
						<% end %>
					<% end %>
				</div>
			</div>
		</table>

		<% unless @user.standard? %>
			<table class="table">
				<div class="media">
					<div class="media-body">
						<h4 class="text-center">My Private Wikis</h4>
						<% @user.wikis.each do |wiki| %>
							<% if wiki.private %>
								<tr>
									<td>
										<h4 class="media-heading"><%= link_to wiki.title, wiki %>
										<small>
											<% if wiki.private %>
												- <strong>Private</strong>
											<% end %>
											<% if wiki.collaborators.any? %>
												- <strong>Collaborators</strong>
											<% end %>
											 - Updated <%= time_ago_in_words(wiki.updated_at) %> ago.
										 </small>
									 </h4>
								 </td>
									<td width="3rem"><%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-default" %></td>
								</tr>
							<% end %>
						<% end %>
					</div>
				</div>
			</table>
		<% end %>

		<% if @user.collab_wikis.any? %>
			<table class="table">
				<div class="media">
					<div class="media-body">
						<h4 class="text-center">Collaborative Wikis</h4>
						<% @user.collab_wikis.each do |wiki| %>
								<tr>
									<td>
										<h4 class="media-heading"><%= link_to wiki.title, wiki %>
										<small>
											<% if wiki.private %>
												- <strong>Private</strong>
											<% end %>
											<% if wiki.collaborators.any? %>
												- <strong>Collaborators</strong>
											<% end %>
											 - Updated <%= time_ago_in_words(wiki.updated_at) %> ago.
										 	</small>
									 	</h4>
									 	<small>Created by <%= wiki.user.name %></small>
								 </td>
									<td width="3rem"><%= link_to "Edit", edit_wiki_path(wiki), class: "btn btn-default" %></td>
								</tr>
						<% end %>
					</div>
				</div>
			</table>
		<% end %>
	</div>
</div>
<!-- <div class="text-center">
	<%= link_to "New Wiki", new_wiki_path, class: "btn btn-primary btn-lg" %>
</div> -->

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
	<div class="col-md-4">
		<h4>Guidelines for Wikis</h4>
		<p class="lead">Here are some general guidelines and good ideas for posting new wikis.</p>
	</div>

	<div class="col-md-8">
		<%= render partial: 'form', locals: {wiki: @wiki} %>
	</div>
</div>

app/views/wikis/show.html.erb
<h1 class=""><%= @wiki.title %>
	<% if @wiki.private %>
		<small> - Private</small>
	<% end %>
</h1>
<div class="row">
	<div class="col-md-9">
		<small>
			Created <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %>
		</small>
		<div class="media">
			<article class="media-body">
				<p class="lead"><%= markdown @wiki.body %></p>
			</article>
		</div>
	</div>

	<div class="col-md-3">
		<% if @wiki.private %>
			Created by <%= @wiki.user.name %>
			<h4>Wiki Collaborators:</h4>
			<% if @wiki.collaborators.any? %>
				<% @wiki.collaborators.each do |c| %>
					<h6 class="text-muted">
						<%= "#{c.user.name} - (#{c.user.email})" %>
					</h6>
				<% end %>
			<% else %>
				<p class="lead">Edit the wiki to add collaborators.</p>
			<% end %>
		<% elsif current_user && current_user.standard? %>
			<div class="text-center"><%= link_to "Upgrade to Premium", new_charge_path, class: "btn btn-primary btn-lg" %></div>
		<% end %>
	</div>
</div>
<div class="text-center">
	<%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-default btn-lg" %>
	<% if current_user && current_user.admin? || @wiki.user == current_user %>
		<%= link_to "Delete", @wiki, method: :delete, class: "btn btn-danger btn-lg", data: {confirm: "Are you sure you want to delete this wiki?"} %>
	<% end %>
</div>