config/routes.rb
Rails.application.routes.draw do

	resources :charges, only: [:new, :create]
	resources :wikis do
		resources :collaborators, only: [:create, :destroy]
	end

	get 'my_wikis' => 'wikis#my_wikis'
	get 'cancel_charge' => 'charges#cancel'
	get 'cancelling_charge' => 'charges#cancelling'

  devise_for :users, controllers: {registrations: "registrations"}
  get 'about' => 'welcome#about'

	root 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	Stripe.api_key = ENV['STRIPE_SECRET_KEY']

	def create
		# Creates a Stripe Customer object, for associating with the charge
		customer = Stripe::Customer.create(
			email: current_user.email,
			card: params[:stripeToken]
		)

		# The charge
		charge = Stripe::Charge.create(
			customer: customer.id, # Note -- This is NOT the user_id
			amount: Amount.default,
			description: "Premium Membership - #{current_user.name}, #{current_user.email}",
			currency: 'usd'
		)

		# Updates current_user.role to "premium"
		current_user.premium!

		flash[:notice] = "Thank you for your payment, #{current_user.name}! Your account has been upgraded to Premium!"
		redirect_to edit_user_registration_path # Or wherever they should be redirected after payment.

		# Stripe will send back CardErrors, with friendly messages when something goes wrong.
		# This 'rescue block' catches and displays those errors
		rescue Stripe::CardError => e
			flash[:alert] = e.message
			redirect_to new_charge_path
	end

	def new
		@stripe_btn_data = {
			key: "#{ Rails.configuration.stripe[:publishable_key] }",
			description: "Premium Membership - #{current_user.name}",
			amount: Amount.default
		}
	end

	def cancelling
	end

	def cancel
		# Stripe action if subscription

		# Update current_user.role to "standard"
		current_user.standard!
		# Update current_user private wikis to public
		current_user.wikis.each do |w|
			w.private = false
			w.save
		end
		flash[:notice] = "Your account has been successfully downgraded to a Standard user."
		redirect_to edit_user_registration_path(current_user)
	end
end

app/views/charges/cancelling.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="media jumbotron">
			<div class="media-body text-center">
				<h3>Not into Premium?</h3>
				<br />
				<p class="lead">No problem. If you would like to cancel Premium and go back to a Standard user please press the button below.</p>
				<p class="lead"><b>Please note</b>, if you downgrade to a Standard user account your private wikis will be made public.</p>
				<p class="lead">We will miss you! Feel free to upgrade to Premium again in the future!</p>
				<br />
				<%= link_to "Cancel Premium", cancel_charge_path, class: "btn btn-danger", data: {confirm: "Please note, downgrading to Standard will make your private wikis public. Are you sure you want to downgrade to Standard?"} %>
				<!-- Stripe Logic if subcription -->
			</div>
		</div>
	</div>
</div>

app/views/charges/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="media jumbotron">
			<div class="media-body text-center">
				<h3>Upgrade to Premium!</h3>
				<br />
				<p class="lead">As a Premium user, you have all of the same capabilities as a Standard user but, you can also create <b>private wikis</b> that are only visible to you. Additionally, you can add other Wikiport users as collaborators on your private wikis!!</p>
				<p class="lead">Upgrading to Premium only costs <b>$10!</b></p>
				<br />
				<%= form_tag charges_path do %>
					<h4>Upgrade to Premium now!</h4>
					<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
				<% end %>
			</div>
		</div>
	</div>
</div>