config/routes.rb
Rails.application.routes.draw do

	resources :charges, only: [:new, :create]
	resources :wikis do
		resources :collaborators, only: [:create, :destroy]
	end

	get 'my_wikis' => 'wikis#my_wikis'
	get 'cancel_charge' => 'charges#cancel'
	get 'cancelling_charge' => 'charges#cancelling'

  devise_for :users, controllers: {registrations: "registrations"}
  get 'about' => 'welcome#about'

	root 'welcome#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>">
		<a href="#" data-dismiss="alert" class="close">&times;</a>
		<ul>
			<li>
				<%= value %>
			</li>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiPort</title>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Navigation -->
	<div class="container-fluid">
		<nav class="navbar nav nav-tabs">
			<%= link_to "Wikiport", root_path, class: "navbar-brand" %>
			<% if user_signed_in? %>
				<%= link_to "My Wikis", my_wikis_path, class: "navbar-brand" %>
			<% else %>
				<%= link_to "Wikis", wikis_path, class: "navbar-brand" %>
			<% end %>
			<div class="pull-right user-info">
				<% if user_signed_in? %>
			   	Hello <strong><%= current_user.name %></strong>! |
			   	<%= link_to 'Edit Profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default'  %>
			 	<% else %>
			   	<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
			   	<%= link_to "Sign In", new_user_session_path, class: 'btn btn-default'  %>
			 	<% end %>
			</div>
		</nav>
		<hr class="navbar-hr" />
	</div>

	<div class="container">

		<%= render 'layouts/messages' %>

		<%= yield %>
	</div>

</body>
</html>